#!/bin/bash
clear
echo "Hi, $USER"
rspec spec/requests/main_tests_spec.rb --format progress --format documentation --out rspec.txt
INFO="$(tail -4 "rspec.txt")"
VALUE=" 0 failures"
TESNUMBER=${INFO:0:1}
echo
if [[ $INFO =~ .*$VALUE.* ]];
then
clear
echo  "You have passed test number $TESNUMBER"
echo  "_______________________________________
|                                     |
|                                     |
|             YOU WON!!!!!            |
|                                     |
|                                     |
|                                     |
---------------------------------------"
else
echo "YOU DONT PASSED all tests please try again"
git add --all
git reset --hard HEAD
#exit 1
fi
echo